=== Hpjhpjhs/UoM_master/WebData/Modelling Data/Week3/Week3/persontypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="PersonList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" type="PersonType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="DoB" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="friend" type="xs:boolean" default="true"/>
        <xs:attribute name="phone" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="LongPersonType">
        <xs:complexContent>
            <xs:extension base="PersonType">
                <xs:sequence>
                    <xs:element name="address" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== Hpjhpjhs/UoM_master/WebData/Modelling Data/Week3/personInstance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<PersonList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="persontypes.xsd">
  
  <person phone="2">
    <Name>Peter</Name>
    <DoB>1966-05-04</DoB>
  </person>
  
  <person xsi:type="LongPersonType" phone="5432" friend="0">
    <Name>Paul</Name>
    <DoB> 1967-05-04</DoB>
    <address> Manchester</address>
  </person>
  
  <person xsi:type="LongPersonType" phone="5433">
    <Name> Mardy</Name>
    <DoB> 1968-05-04</DoB>
    <address> Liverpool</address>
  </person>
  
</PersonList>
